Creacion de aplicacion y testeo con firebase
Hanagotchi/app-mobile pull request #1
Opened 2024-03-22 22:32 UTC by Agustinefe

- Se crea el proyecto mobile con una app dummy.
- La app esta preparada para ejecutarse a traves de la APK.
- Las instrucciones sobre como levantar la app esta en el readme.
- Se definio una arquitectura tentativa para el proyecto.
- Se creo un boton custom :3.
- Se testeo la integracion con firebase y funciona.

2024-03-22 22:34 UTC, fjpacheco approved these changes

2024-03-22 22:44 UTC, fjpacheco requested changes

2024-03-22 22:44 UTC, fjpacheco commented on hanagotchi-app/.gitignore
> +# Learn more https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files
EL READMEEEEEEEE

2024-03-22 23:22 UTC, Agustinefe commented on hanagotchi-app/.gitignore
> +# Learn more https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files
:D

2024-03-23 00:01 UTC, fjpacheco approved these changes

2024-03-23 18:03 UTC, feijooso commented on README.md
> +Dentro de la carpeta FiuFit ejecutar:
carpeta hanagotchi-app no?

2024-03-23 18:10 UTC, Agustinefe commented on README.md
> +Dentro de la carpeta FiuFit ejecutar:
xd

2024-03-23 23:57 UTC, feijooso approved these changes
tuve que upgradear obligatoriamente mi node a la v18.18.2 pero con eso levanto bien

2024-03-24 00:52 UTC, merged