Han 75: Agregado de soporte para api de clima.
Hanagotchi/app-mobile pull request #18
Opened 2024-04-20 05:24 UTC by Agustinefe

## Linked ticket in Jira
- https://hanagotchi.atlassian.net/browse/HAN-75

## Describe your changes, marking the new features and possible risks
- Se ha incorporado el servicio de api de clima.
- Cuando se fetchee una medicion y esta vuelva vacia, se asumira que no tiene sensor, y se enviara una medicion.
- Para evitar leer constantemente la api de clima, se creo una cache que se renueva cada 5 minutos.
- Aquellas mediciones que provengan de openWeather mostraran el logo de openWeather en la parte superior derecha.
- Se mejoro el display de la hora de la medicion.
- Se ocultaron los botones del carrousel de plantas cuando se llega a sus extremos.
- Se cambio el color a rojo cuando una medicion esta desviada (en un futuro, habria que agregar que hacer frente a esos casos).
- Se linkeo el boton de añadir bitacora con la screen de creacion de bitacoras. Al redirigirse, autocompleta el campo de planta.

## Media: upload photos or videos (if needed)
![image](https://github.com/Hanagotchi/app-mobile/assets/56854562/68a3fe45-6cd1-4022-9365-c009a38c32bc)
![image](https://github.com/Hanagotchi/app-mobile/assets/56854562/0e094f77-ce8e-497f-8fc4-a79fc71553f8)

2024-04-20 17:39 UTC, fjpacheco requested changes

2024-04-20 17:39 UTC, fjpacheco commented on hanagotchi-app/src/components/home/PlantInfo.tsx
> +                    if (myUser?.location) {
esto no se fetchea bien, incia con Null y me aparece asi

![image](https://github.com/Hanagotchi/app-mobile/assets/51347305/1fbf2df0-1e37-4637-9e48-ab259cac4473)

pero cuando edito codigo forzando a que haga el fetch (editando un cambio en esta pantalla y guardando con ctrl +s para que se recargue, ahi si aparece mi user con location

![image](https://github.com/Hanagotchi/app-mobile/assets/51347305/d72b15dd-bb21-44d5-9955-064ef33fa172)

va joya

2024-04-20 17:39 UTC, fjpacheco commented on hanagotchi-app/src/hooks/useMyUser.tsx
No se si ameritaba en este PR, pero esta implicito:

Si yo quiero cambiar mi ubicacion desde la pantalla de editar usuario, estaria bueno que se actualice el contexto de mi usuario, y de ahi se limpie la "cache" (weatherCache) para que cargue la nueva location

quise probar con un lugar de USA para ver si hace frio pero si o is debo cerrar app y leugo hacer ese reload manual en la pantalla de plantinfo para que me cargue la nueva ubicacion

2024-04-20 17:40 UTC, fjpacheco commented
para los que prueben recordar agregar a loader.ts

`openWeatherApiUrl: "https://api.openweathermap.org",`    

`openWeatherAppId: "........"` (esta en el body de jira https://hanagotchi.atlassian.net/browse/HAN-75)

2024-04-20 17:52 UTC, Agustinefe commented on hanagotchi-app/src/hooks/useMyUser.tsx
Podria guardar la location en Zustand. Si veo que no es complicado lo hago.

2024-04-20 19:58 UTC, Agustinefe commented on hanagotchi-app/src/components/home/PlantInfo.tsx
> +                    if (myUser?.location) {
Seguramente no te agregaste la url de openWeather en el loader porque sos un perversito

2024-04-21 01:09 UTC, Agustinefe commented on hanagotchi-app/src/hooks/useMyUser.tsx
Bueno, me parece que te lo debo para otro ticket. Es mucho ajajjajaja

2024-04-21 17:10 UTC, feijooso requested changes
El logo de la api queda raro ahi arriba, lo pondria en la parte inferior de la cajita. Arriba del ultima actualizacion ponele.

2024-04-23 02:24 UTC, Agustinefe commented
> El logo de la api queda raro ahi arriba, lo pondria en la parte inferior de la cajita. Arriba del ultima actualizacion ponele.

![image](https://github.com/Hanagotchi/app-mobile/assets/56854562/ef0aa60e-989c-44f2-9b7b-04ef7d3b52f8)
@feijooso asi? Capaz si incluimos alguna medicion extra de otra API puede haber conflictos, pero por el momento no jode y se ve bien.

2024-04-23 17:07 UTC, fjpacheco approved these changes

2024-04-24 14:41 UTC, feijooso approved these changes

2024-04-24 14:56 UTC, merged