Han 65: Pagina de login
Hanagotchi/app-mobile pull request #2
Opened 2024-03-26 19:09 UTC by Agustinefe

## Linked ticket in Jira
[- https://hanagotchi.atlassian.net/jira/software/projects/HAN/boards/1/backlog](https://hanagotchi.atlassian.net/browse/HAN-65)

## Describe your changes, marking the new features and possible risks
- Se creo la pantalla de login que interactua con Google y con la api de Hanagotchi.
- Se creo un sistema de navegacion de pantallas basico. Este sistema incluye un bottom tab (sin estilizar) que permite la navegacion entre las cuatro pantallas principales de la aplicacion.
- Al logearse, se guardan los datos del usuario en el secure storage (los que devuelve la api).
- Se implementa un boton de log out en la pantalla de Settings (previamente llamada perfil).
- Se agrego una pantalla de splash (sin logo) que precede a la primera pantalla que ve el usuario.

## Tests
La app ha sido testeada en un dispositivo Android. Se desconoce como es su performance en un dispositivo Ios.

## Media: upload photos or videos (if needed)
-

2024-03-26 23:32 UTC, Agustinefe commented
Se agrego un componente Loader Button y un Error boundary

2024-03-27 02:47 UTC, fjpacheco commented
![Screenshot 2024-03-26 at 23 46 55](https://github.com/Hanagotchi/app-mobile/assets/51347305/46012010-6ade-413d-98ee-fc46a905ab58)

Me tiro este error la primera vez que me registre, raro. Lo dejo documentado aca en el PR

2024-03-27 02:48 UTC, fjpacheco commented
![Screenshot 2024-03-26 at 23 48 07](https://github.com/Hanagotchi/app-mobile/assets/51347305/92524d4e-9a2f-47d8-b2fc-04409503a699)
Independientemente del error, anda todo piola. Probe borrando la cuenta registrada desde el panel de Firebase tambien https://console.firebase.google.com/u/1/project/hanagotchi/authentication/users?hl=es-419

2024-03-27 02:53 UTC, fjpacheco requested changes

2024-03-27 02:53 UTC, fjpacheco commented on hanagotchi-app/src/environment/loader.example.ts
> +}
Falta `googleWebClientId`

2024-03-27 02:53 UTC, fjpacheco commented on hanagotchi-app/src/environment/loader.example.ts
> +}
Dejarlo documentado en algún lado recordando que hay que editar estas variables de entorno. Para mi re va documentarlo en el `README.md` y también en el `loader.example.ts` así recuerda el developer que debe crear su propio `loader.ts` (no es tan intuitivo como el `.env`).

Documentar que `googleWebClientId` se la puede obtener desde el panel de Heroku, en al seccion de las variables de entorno del microservicio de mediciones (idem con las URLs, aunque a futuro sera una única URL...)

2024-03-27 02:53 UTC, fjpacheco approved these changes

2024-03-27 04:06 UTC, feijooso commented
tengo el mismo error que pach en el 1er login

2024-03-27 13:25 UTC, Agustinefe commented on hanagotchi-app/src/environment/loader.example.ts
> +}
El .env me tiraba conflictos con cosas en la build. Tendria que investigarse mas. Por eso a priori opte por definir un json dentro de un .ts

2024-03-28 03:35 UTC, Agustinefe commented
El problema del primer login surge debido a un fallo en la api de users.

Cuando se logea un usuario por primera vez, no se esta devolviendo el user creado (actualmente retorna un json vacio, y es ahi donde Zod explota)

Se arreglo este problema en este PullRequest: https://github.com/Hanagotchi/users/pull/5

2024-03-28 04:07 UTC, Agustinefe commented
Resolvi un problema de un warning que se lanzaba cuando se cancelaba el login. Ya no pasa

2024-03-28 04:27 UTC, fjpacheco commented
listo probando anda joya pegandole a la nube y local

2024-03-28 04:27 UTC, merged