Han 122: Pantalla de busqueda
Hanagotchi/app-mobile pull request #33
Opened 2024-06-09 18:21 UTC by Agustinefe

## Linked ticket in Jira
- https://hanagotchi.atlassian.net/browse/HAN-122

## Describe your changes, marking the new features and possible risks
- Se implemento una pantalla de busqueda.
- Se pueden buscar publicaciones taggeadas, y usuarios por nickname.
- No se pueden ingresar whitespaces en la busqueda.
- Se arreglo el problema de la lista de posteos que reiniciaba la posicion de la lista al fetchear nuevos datos.
- Se arreglo el problema del doble refresh de la lista.

## Media: upload photos or videos (if needed)
![image](https://github.com/Hanagotchi/app-mobile/assets/56854562/12ce0bdf-4827-4a45-87c7-c2fa169a2b47)
![image](https://github.com/Hanagotchi/app-mobile/assets/56854562/3acc8a12-a1c8-442e-b304-cb42aa03390a)

2024-06-11 02:58 UTC, feijooso requested changes
1. al entrar a la lupita tengo este warning
![photo_2024-06-10_23-55-29](https://github.com/Hanagotchi/app-mobile/assets/23175368/40350ae6-3e49-49c9-a84b-22c9c41fe8f1)
2. tanto buscar publis como tags me devuelve 400. Igual la primera vez que busque un tag me anduvo, pero despues cree una publi nueva con tags y no me encuentra la publi. Para users nunca me anduvo
![photo_2024-06-10_23-55-28](https://github.com/Hanagotchi/app-mobile/assets/23175368/fb09a93c-91f3-44b0-8875-f5457451ad08)
![photo_2024-06-10_23-55-26](https://github.com/Hanagotchi/app-mobile/assets/23175368/508e4997-5da3-4b28-95c7-5f3434329451)

2024-06-11 13:07 UTC, Agustinefe commented
> 1. al entrar a la lupita tengo este warning
>    ![photo_2024-06-10_23-55-29](https://private-user-images.githubusercontent.com/23175368/338418177-40350ae6-3e49-49c9-a84b-22c9c41fe8f1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTEwOTksIm5iZiI6MTcxODExMDc5OSwicGF0aCI6Ii8yMzE3NTM2OC8zMzg0MTgxNzctNDAzNTBhZTYtM2U0OS00OWM5LWE4NGItMjJjOWM0MWZlOGYxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEyNTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMDBiMTQ3MjEzNjE1MjVhNGYwMmI4NThhOTRjZGM3ZGRlYzIzMmVkMTc5YmU5NjVjM2U5NTRhMzg2ZTIzMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LLl_2ai3phphpLljwMkrhMN1QB8Bi4H8lr-WY7GcVD0)
> 2. tanto buscar publis como tags me devuelve 400. Igual la primera vez que busque un tag me anduvo, pero despues cree una publi nueva con tags y no me encuentra la publi. Para users nunca me anduvo
>    ![photo_2024-06-10_23-55-28](https://private-user-images.githubusercontent.com/23175368/338418546-fb09a93c-91f3-44b0-8875-f5457451ad08.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTEwOTksIm5iZiI6MTcxODExMDc5OSwicGF0aCI6Ii8yMzE3NTM2OC8zMzg0MTg1NDYtZmIwOWE5M2MtOTFmMy00NGIwLTg4NzUtZjU0NTc0NTFhZDA4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEyNTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlODM1ZDM5YjlkZTEzZDk0ZTYzZDFlMWU3NWEwMjdkNmUyMDVhYjI4ZjEyYjBjZDk4YzhiYWY3YTI4ZDM0NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vbbQ-6wFYm2y-M-ixTHpBtENQCHK1Z_UzYZfBgCpeQ0)
>    ![photo_2024-06-10_23-55-26](https://private-user-images.githubusercontent.com/23175368/338418552-508e4997-5da3-4b28-95c7-5f3434329451.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTEwOTksIm5iZiI6MTcxODExMDc5OSwicGF0aCI6Ii8yMzE3NTM2OC8zMzg0MTg1NTItNTA4ZTQ5OTctNWRhMy00YjI4LTk1YzctNWYzNDM0MzI5NDUxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEyNTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMGU0Y2ExZmIyOGNkMzMxN2I0ODA3ZjdhZmJjZTA1N2E0MDk5NjRmZTg0Yjc5NzVmNjVkY2YxZDFlMWJkMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z7ACwigVwCzVlgiItKz0nUG3SP6FmMu9FuwqiaFy7T8)

1. Es un warning que tira la primera vez, dado que esta actualizando el header y la screen y no puede hacerlo en el mismo ciclo de renderizado. Por ahora nunca trajo problemas.
2. Olvide mencionar que para que funcione esta pantalla se requiere que [este PR](https://github.com/Hanagotchi/social/pull/15) este mergeado en main (o al menos deployar manualmente la branch en heroku). Por eso no te andaba el fetch de usuarios. Respecto al de publicaciones, probablemente sea el 503 que hablamos anteriormente. Si pudiese replicarlo, ¿podrias pasarme los logs?

2024-06-11 13:18 UTC, Agustinefe commented
Agregue un timer al searchbar para que la busqueda se ejecute 0.5 segundos luego de dejar de escribir. Esto permite reducir el spameo de requests al backend, rogando para que no vuelva a tirar esos 503 feitos.

2024-06-12 21:23 UTC, feijooso approved these changes
looking good

2024-06-12 21:58 UTC, merged