Han-67 Home screen
Hanagotchi/app-mobile pull request #5
Opened 2024-04-01 02:29 UTC by feijooso

## Linked ticket in Jira
- https://hanagotchi.atlassian.net/browse/HAN-67

## Describe your changes, marking the new features and possible risks
-

## Media: upload photos or videos (if needed)
-

2024-04-11 19:08 UTC, Agustinefe commented on hanagotchi-app/src/contexts/HanagotchiServiceContext.tsx
> +  baseURL: "https://gateway-hanagotchi-2849a3fb624a.herokuapp.com/"
👁️ 👄 👁️

2024-04-11 19:09 UTC, Agustinefe commented on hanagotchi-app/src/models/Measurement.ts
> +})
Faltaria el campo nuevo deviations. Actualmente tira error de Zod.

2024-04-14 16:29 UTC, fjpacheco requested changes
Al iniciar sesion por primera vez me sale asi:
  
  ![image](https://github.com/Hanagotchi/app-mobile/assets/51347305/d5599e19-dc92-4292-9d2e-de58d63abcfc)
  Creo que es porque llama al endpoint inicialmente con `/measurements/0/last` (a la izq. son los logs de gateway de heroku.. se obtienen con `heroku logs -t -a gateway-hanagotchi`.
  Lo raro es que si interacuto con los botones de navegacion, ahi si me anda y aparece las mediciones:
  ![image](https://github.com/Hanagotchi/app-mobile/assets/51347305/fccb5cec-4d21-4a7c-8127-fe40f02d3cff)
  
  Hay un warning amarillo raro, y si le doy click me sale esto:
  ![image](https://github.com/Hanagotchi/app-mobile/assets/51347305/f1938916-3ba1-4eac-8055-135460be3f65)
  
  Nada, seria revisar esas cositas
  y yo quitaria los botones de naavegacion si tenes solo 1 planta registrada como yo jeje
  Tambien ajustaria el boton de info o de create logs, los veo re juntitos. Lo dejaria abajito como en las wireframes

2024-04-18 14:26 UTC, Agustinefe approved these changes

2024-04-19 02:52 UTC, fjpacheco approved these changes

2024-04-19 02:53 UTC, fjpacheco approved these changes

2024-04-19 03:04 UTC, merged