HAN-68: Edit profile
Hanagotchi/app-mobile pull request #7
Opened 2024-04-01 04:45 UTC by feijooso

## Linked ticket in Jira
- https://hanagotchi.atlassian.net/browse/HAN-68

## Describe your changes, marking the new features and possible risks
-

## Media: upload photos or videos (if needed)
-

2024-04-11 13:46 UTC, Agustinefe requested changes
Algunas cosas que note:
- El loader deberia estar centrado (con agregarle un {justifyContent: "center"} al style deberia alcanzar).
- Estaria bueno agregarle un poco de margin bottom al boton de Guardar, para que no quede pegado al borde de la pantalla.
- Todos los accesos del tab de configuracion deberian estar en la parte superior de la pantalla y seguir el formato del wireframe. Actualmente lo veo asi en mi celu.
![image](https://github.com/Hanagotchi/app-mobile/assets/56854562/03124dd2-4df2-40bf-bf38-de8445528bd1)

2024-04-11 13:46 UTC, Agustinefe commented on hanagotchi-app/src/screens/ProfileScreen.tsx
> +                </View>
No es necesario hacer un header custom; desde el navigator podes setearle el header en los options y te crea el header automaticamente.

2024-04-13 19:31 UTC, feijooso commented on hanagotchi-app/src/screens/ProfileScreen.tsx
> +                </View>
cambiado

2024-04-14 01:01 UTC, fjpacheco approved these changes

2024-04-14 01:05 UTC, fjpacheco approved these changes

2024-04-14 16:18 UTC, Agustinefe approved these changes

2024-04-14 18:28 UTC, merged